### ISSUE TITLE
ban物品zs魔改

### ISSUE THREAD

**Issue by zero6six** [mcstaralliance/ZenScript#1]
[ban.zip](https://github.com/mcstaralliance/ZenScript/files/4639980/ban.zip)

**Comment by LDS-XiaoYe** [comment]
@zero6six 收到，审核近期开始。

**Comment by zero6six** [comment]
`//凝血弹弓,方块放置器,UU一套,稳定刷怪笼未ban

//无尽碗
import mods.roots.Fey;
Fey.removeRecipe(<roots:unending_bowl>);

//祛魔台
recipes.remove(<draconicevolution:diss_enchanter>);

//苍穹变换器
recipes.remove(<draconicevolution:celestial_manipulator>);

//空间IO端口
recipes.remove(<appliedenergistics2:spatial_io_port>);

//地形转换机
recipes.remove(<ic2:te:40>);

//反应堆稳定器
recipes.remove(<draconicevolution:reactor_component>);

//空间塔
recipes.remove(<appliedenergistics2:spatial_pylon>);

//反应堆能量注入器
recipes.remove(<draconicevolution:reactor_component:1>);

//资源库
recipes.remove(<armourers_workshop:tile.skin-library>);

//发电机
recipes.remove(<draconicevolution:generator>);

//采矿机
recipes.remove(<ic2:te:60>);

//高级采矿机
recipes.remove(<ic2:te:57>);

//全球资源库
recipes.remove(<armourers_workshop:tile.global-skin-library>);

//时装制作台
recipes.remove(<armourers_workshop:tile.armourer>);

//气象方尖碑
recipes.remove(<enderio:block_weather_obelisk>);

//信箱
recipes.remove(<forestry:mailbox>);

//贸易站
recipes.remove(<forestry:trade_station>);

//集邮箱
recipes.remove(<forestry:stamp_collector>);

//造雨机
recipes.remove(<forestry:rainmaker>);

//林业背包
recipes.remove(<forestry:lepidopterist_bag>);
recipes.remove(<forestry:miner_bag>);
recipes.remove(<forestry:digger_bag>);
recipes.remove(<forestry:forester_bag>);
recipes.remove(<forestry:hunter_bag>);
recipes.remove(<forestry:apiarist_bag>);
recipes.remove(<forestry:adventurer_bag>);
recipes.remove(<forestry:builder_bag>);

//区块加载器
recipes.remove(<ic2:te:82>);

//玄钢头盔
recipes.remove(<enderio:item_dark_steel_helmet>);

//玄钢胸甲
recipes.remove(<enderio:item_dark_steel_chestplate>);

//玄钢护腿
recipes.remove(<enderio:item_dark_steel_leggings>);

//玄钢靴子
recipes.remove(<enderio:item_dark_steel_boots>);

//末影钢头盔
recipes.remove(<enderio:item_end_steel_helmet>);

//末影钢胸甲
recipes.remove(<enderio:item_end_steel_chestplate>);

//末影钢护腿
recipes.remove(<enderio:item_end_steel_leggings>);

//末影钢靴子
recipes.remove(<enderio:item_end_steel_boots>);

//ME破坏面板
recipes.remove(<appliedenergistics2:part:300>);

//ME流体破坏面板-AE2
recipes.remove(<appliedenergistics2:part:302>);

//ME流体破坏面板-更多元件
recipes.remove(<extracells:part.base:5>);

//传送符咒
recipes.remove(<draconicevolution:dislocator>);

//全息投影仪
recipes.remove(<armourers_workshop:tile.hologram-projector>);
[ban.zip](https://github.com/mcstaralliance/ZenScript/files/4667915/ban.zip)


//生物球可复用生物球
recipes.remove(<thermalexpansion:morb>);

//可复用生物球
recipes.remove(<thermalexpansion:morb:1>);

//工业tnt
recipes.remove(<ic2:te:1>);

//工程师装配台
recipes.remove(<immersiveengineering:wooden_device0:2>);

//左轮手枪
recipes.remove(<immersiveengineering:revolver>);

//折返权杖
recipes.remove(<enderio:item_rod_of_return>);

//方块破坏器
recipes.remove(<industrialforegoing:block_destroyer>);

//旅行权杖
recipes.remove(<enderio:item_travel_staff>);

//无限钻头
recipes.remove(<industrialforegoing:infinity_drill>);

//杀手乔
recipes.remove(<enderio:block_killer_joe>);

//核弹
recipes.remove(<ic2:te:2>);

//武士头盔
recipes.remove(<sakura:samurai_helmet>);

//武士胸甲
recipes.remove(<sakura:samurai_chest>);

//武士护腿
recipes.remove(<sakura:samurai_pants>);

//武士靴子
recipes.remove(<sakura:samurai_shoes>);

//炽焰之啄颅剑
recipes.remove(<avaritia:skullfire_sword>);

//熵变机械臂
recipes.remove(<appliedenergistics2:entropy_manipulator>);

//物品传送符咒
recipes.remove(<draconicevolution:magnet>);

//物质炮
recipes.remove(<appliedenergistics2:matter_cannon>);

//生物捕捉工具
recipes.remove(<industrialforegoing:mob_imprisonment_tool>);

//电动刷怪箱
recipes.remove(<enderio:block_powered_spawner>);

//磁轨炮
recipes.remove(<immersiveengineering:railgun>);

//终结之剑
recipes.remove(<enderio:item_dark_steel_sword>);

//经验交换方尖碑
recipes.remove(<enderio:block_experience_obelisk>);

//绑定传送符咒(点对点)
recipes.remove(<draconicevolution:dislocator_bound:1>);

//绑定传送符咒(玩家)
recipes.remove(<draconicevolution:dislocator_bound:2>);

//网络工具
recipes.remove(<appliedenergistics2:network_tool>);

//自动刷怪机
recipes.remove(<industrialforegoing:mob_duplicator>);

//觉醒物品传送符咒
recipes.remove(<draconicevolution:magnet:1>);

//调色器
recipes.remove(<armourers_workshop:tile.colour-mixer>);

//配色工作台
recipes.remove(<armourers_workshop:tile.dye-table>);

//镶嵌工作台
recipes.remove(<armourers_workshop:tile.skinning-table>);

//ME成型面板
recipes.remove(<appliedenergistics2:part:320>);

//ME流体成型面板-AE2
recipes.remove(<appliedenergistics2:part:321>);

//ME流体成型面板-更多元件
recipes.remove(<extracells:part.base:6>);

//传送台
recipes.remove(<enderio:block_tele_pad>);

//传送符咒基座
recipes.remove(<draconicevolution:dislocator_pedestal>);

//附魔提取机
recipes.remove(<industrialforegoing:enchantment_extractor>);

//灵魂瓶
recipes.remove(<enderio:item_soul_vial>);

//不完善的仪式石
recipes.remove(<bloodmagic:ritual_controller:1>);

//传送符咒收纳容器
recipes.remove(<draconicevolution:dislocator_receptacle>);

//传送试剂
mods.bloodmagic.TartaricForge.removeRecipe
([<bloodmagic:teleposer>, <minecraft:glowstone>, <minecraft:redstone_block>, <minecraft:gold_ingot>]);

//抑液试剂
mods.bloodmagic.TartaricForge.removeRecipe
([<bloodmagic:teleposer>, <minecraft:water_bucket>, <minecraft:lava_bucket>, <minecraft:blaze_rod>]);

//影桥试剂
mods.bloodmagic.TartaricForge.removeRecipe
([<minecraft:soul_sand>, <minecraft:soul_sand>, <minecraft:obsidian>, <minecraft:stone>]);

//移位试剂(bug)
mods.bloodmagic.TartaricForge.removeRecipe
([<bloodmagic:teleposer>, <minecraft:diamond>, <minecraft:ender_pearl>, <minecraft:obsidian>]);

//玄钢升级"存入"
recipes.remove(<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:direct"}));

//玄钢升级"旅行"
recipes.remove(<enderio:item_dark_steel_upgrade:1>.withTag({"enderio:dsu": "enderio:travel"}));

//信件
recipes.remove(<forestry:letters>);
mods.forestry.Carpenter.removeRecipe(<forestry:letters>);

//EFLN
recipes.remove(<tconstruct:throwball:1>);`

**Comment by zero6six** [comment]
[ban.zip](https://github.com/mcstaralliance/ZenScript/files/4667919/ban.zip)
添加无尽碗魔改

**Comment by LDS-XiaoYe** [comment]
@zero6six 因 BloodMagic 已在下周目删除，你应当删除关于 BloodMagic 物品的魔改代码。

**Comment by GMengZhi-Github** [comment]
@zero6six Oh my god

**Comment by zero6six** [comment]
[ban.zs.txt](https://githu.com/mcstaralliance/ZenScript/files/4671732/ban.zs.txt)
@LDS-XiaoYe 新端给一个秋梨膏?

**Comment by GMengZhi-Github** [comment]
@zero6six 我直接+1

**Comment by GMengZhi-Github** [comment]
@GMengZhi-Github 好的

**Comment by LDS-XiaoYe** [comment]
暂时接受，批量删除合成时善用 var 数组，循环删除。

**Comment by GMengZhi-Github** [comment]
@LDS-XiaoYe 我同意 建议看以前的模组 循环删除木板合成表

**Comment by zero6six** [comment]
彳亍


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LDS_XiaoYe"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月23日(星期六) 晚上8:29
收件人:&nbsp;"mcstaralliance/ZenScript"<ZenScript@noreply.github.com&gt;;
抄送:&nbsp;"2656428055"<2656428055@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [mcstaralliance/ZenScript] ban物品zs魔改 (#1)





 
暂时接受，批量删除合成时善用 var 数组，循环删除。
