### ISSUE TITLE
建议删除所有项目内的Lib.zs

### ISSUE THREAD

**Issue by Dabai1025** [mcstaralliance/ZenScript#101]
版权问题
所有 Lib.zs 代码均为 youyihj 所著
[https://github.com/friendlyhj/FlyingRoad3/blob/master/scripts/classes/youyihjLib.zs](url)

**Comment by LDS-XiaoYe** [comment]
同意删除。
若另有需要，将重新创建一个专门存放 Lib 的仓库并使用 CC BY-NC-SA 4.0 分发。
