### ISSUE TITLE
Stupid ic2 plate fix (machine)

### ISSUE THREAD

**Issue by GMengZhi-Github** [mcstaralliance/ZenScript#4]
[metal_former_rolling.ini.txt](https://github.com/mcstaralliance/ZenScript/files/4671519/metal_former_rolling.ini.txt)
删除这个txt后缀名然后甩到config文件夹里

**Comment by GMengZhi-Github** [comment]
所有的金属成型机辊压出板全部为热力膨胀的板子

**Comment by LDS-XiaoYe** [comment]
wait for checking

**Comment by GMengZhi-Github** [comment]
@LDS-XiaoYe 彳亍

**Comment by LDS-XiaoYe** [comment]
暂无统一各模组板需求，暂时接受。
